# File: .streamlit/secrets.toml

[supabase]
url = "https://rozotbphfdomckvjpjse.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvem90YnBoZmRvbWNrdmpwanNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MzI3NDUsImV4cCI6MjA3MTQwODc0NX0.YiHg0VYpJj4C4Qod228JJxaJU2SRTEyjHGAa94DJA7Q"